<?xml version="1.0"?>
<package format="3"> 
  <name>bosch_navigator_bridge</name>
  <version>2.1.16</version>
  <description>ROS interface to Rexroth ROKIT Navigator</description>
  <maintainer email="Fabian.Koenig@boschrexroth.de">Fabian Koenig</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>launch_xml</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>

  <depend>libpoco-dev</depend>
  
  
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
