name: "Build action (utils): Galactic"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run once per day to detect broken dependencies.
    - cron: '33 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ ubuntu-20.04, windows-latest, macOS-latest ]
        os: [ ubuntu-20.04 ]
        ros_distribution: [ galactic ]
    steps:
    - uses: ros-tooling/setup-ros@v0.5
      with:
        required-ros-distributions: ${{ matrix.ros_distribution }}
    - uses : ros-tooling/action-ros-ci@v0.3
      with:
        package-name: bosch_locator_bridge_utils
        vcs-repo-file-url: ''
        target-ros2-distro: ${{ matrix.ros_distribution }}
        colcon-defaults: |
          {
            "build": {
              "mixin": ["coverage-gcc"]
            }
          } 
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
