name: "Build action: Rolling"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run once per day to detect broken dependencies.
    - cron: '33 6 * * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros_distribution: "rolling"
            os: "ubuntu-22.04"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: ros-tooling/setup-ros@v0.6
      with:
        required-ros-distributions: ${{ matrix.ros_distribution }}
    - uses : ros-tooling/action-ros-ci@v0.3
      with:
        package-name: bosch_locator_bridge
        vcs-repo-file-url: ''
        target-ros2-distro: ${{ matrix.ros_distribution }}
        colcon-defaults: |
          {
            "build": {
              "mixin": ["coverage-gcc"]
            }
          }
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
