name: "Build action Navigator: Humble"

on:
  push:
    branches: [ humble ]
  pull_request:
    branches: [ humble ]
  schedule:
    # Run once per day to detect broken dependencies.
    - cron: '33 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-${{ matrix.ubuntu_distribution }}-ros-${{ matrix.ros_distribution }}-desktop-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        # Each ROS distribution requires a specific Ubuntu version
        include:
          - ros_distribution: humble
            ubuntu_distribution: jammy
          # To add more distributions, uncomment and adjust:
          # - ros_distribution: iron
          #   ubuntu_distribution: jammy
          # - ros_distribution: jazzy
          #   ubuntu_distribution: noble
    steps:
    - uses : ros-tooling/action-ros-ci@v0.3
      with:
        package-name: bosch_navigator_bridge
        vcs-repo-file-url: ''
        target-ros2-distro: ${{ matrix.ros_distribution }}
        colcon-defaults: |
          {
            "build": {
              "mixin": ["coverage-gcc"]
            }
          }       
        colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
